---
- hosts: localhost
  vars:
   http_port: 80
   max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    apt: name=apache2 state=latest
  - name: write the apache config file 
    template: src=/vagrant/apache2 dest=/etc/init.d/apache2
    notify:
    - restart apache2
  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  handlers:
   - name: restart apache2
     service: name=apache2 state=restarted
  
  tasks:
  - name: ensure mysql is at the latest version
    apt:
     name: mysql-server-5.6
     state: latest
#  - name: Set root password for the first time
#    command: mysqladmin -u root password newpassword 
  - name: The package below solves the error python mysqldb module is required which occurs when you are installing the openmrs database
    apt:
     name: python-mysqldb
     state: latest
  - name: ensure mysql is started
    service:
     name: mysql
     state: running
# install openmrs database
  - mysql_db:
     login_user=root
     login_password=newpassword
     name=openmrs 
     encoding=utf8
     state=present
#source the database into openmrs
  - copy: src=DemoDB.sql dest=/tmp
  - mysql_db: 
     login_user=root
     login_password=newpassword
     name=openmrs
     state=import
     target=/tmp/DemoDB.sql    
