---
  tasks:
  - name: ensure apache is at the latest version
    apt: name=apache2 state=latest
  - name: write the apache config file 
    template: src=/vagrant/apache2 dest=/etc/init.d/apache2
    notify:
    - restart apache2
  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  handlers:
   - name: restart apache2
     service: name=apache2 state=restarted
